server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    #检擦模板是否存在
    check-template: true
    #是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    cache: false
    #模板后缀
    suffix: .html
    #编码格式
    encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
  servlet:
  #上传文件最大值
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  #quartz定时任务配置
  quartz:
    #使用JDBC存储任务
    job-store-type: jdbc
    jdbc:
      #对应表格前缀
      comment-prefix: QRTZ_
      #启动服务时初始化
      initialize-schema: always
    overwrite-existing-jobs: false
  #mail邮箱
  mail:
    host: smtp.163.com
    password: isCcr163mail
    default-encoding: UTF-8
    username: 17301918183@163.com
    #http://help.163.com/09/1223/14/5R7P3QI100753VB8.html
    #163邮箱端口 ssl加密 465 25 QQ邮箱 587
    port: 25
  application:
    name: spring-boot-rabbitmq-sender
  rabbitmq:
    host: 192.168.0.112
    port: 5672
    username: Ccr
    password: 1999ccr..
mail:
 fromMail:
  #邮箱发信人必须与登陆人一致
  addr: 17301918183@163.com
management:
  endpoint:
    health:
      show-details: always
    shutdown: false
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  type-aliases-package: com.crsm.maker.*.mapper
  mapper-locations: classpath*:mapper/*/*.xml
  global-config:
    refresh: true
